#!/usr/bin/python2
# Based on: https://bbs.archlinux.org/viewtopic.php?pid=962423#p962423
# This version is modified to handle mailboxes with spaces in the names

import pyinotify
from os.path import expanduser
from mailbox import MaildirMessage
from email.header import decode_header
from subprocess import call

maildir_folder = expanduser(r"~/Mail/")

# Getting the path of all the boxes
fd =  open(expanduser(r"~/.mutt/mailboxes"), 'r')
# [10:-1] to remove the initial '^mailboxes '
boxes = filter(None, (b.rstrip().replace('+Gmail','') for b in fd.readline()[10:-1].split('"')))
boxesFilter = lambda foldername: foldername in ["/INBOX", "/aos-devel", "/bugzilla", "/container-teams"]
boxes = filter(boxesFilter, boxes)
fd.close()

# Handling a new mail
dec_header = lambda h : ' '.join(unicode(s, e if bool(e) else 'ascii') for s, e in decode_header(h))

def newfile(event):
    fd = open(event.pathname, 'r')
    mail = MaildirMessage(message=fd)
    From = dec_header(mail['From'])
    Subject = "Subject: " + dec_header(mail['Subject'])
    p = '/'.join(event.path.split('/')[-3:-1])
    p = p.replace('Mail/', '')
    n = p+": "+From
    fd.close()
    call(["notify-send", "-i", "gtk-dialog-info", n, Subject])
    call(["paplay", "/usr/share/sounds/gnome/default/alerts/drip.ogg"])

wm = pyinotify.WatchManager()
notifier = pyinotify.Notifier(wm, newfile)

for box in boxes:
    wm.add_watch(maildir_folder+box+"/new", pyinotify.IN_CREATE | pyinotify.IN_MOVED_TO)

notifier.loop()
