export PATH=$PATH:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:$HOME/bin:$HOME/.cargo/bin:$HOME/go/bin
# golang ftw
export PATH=$PATH:/usr/local/go/bin:/home/amurdaca/go/src/github.com/openshift/origin/_output/local/bin/linux/amd64
export GOPATH=$HOME/go
export CDPATH=/home/amurdaca/go/src/github.com/
export WORKON_HOME=$HOME/.venvs
mkdir -p $WORKON_HOME
mkdir -p /tmp/krbcache
KRB5CCNAME=DIR:/tmp/krbcache
export KRB5CCNAME
source /usr/bin/virtualenvwrapper.sh
